// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZEc9XIEmPn02wmtXar0TfJt8qeqJQMhw',
    appId: '1:511621212818:web:1940f8274da0c995e5144b',
    messagingSenderId: '511621212818',
    projectId: 'loginflutter-c5ffa',
    authDomain: 'loginflutter-c5ffa.firebaseapp.com',
    storageBucket: 'loginflutter-c5ffa.firebasestorage.app',
    measurementId: 'G-446XCXY9VQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpbHLM-VxQV6JenBy2adw0UkdU2srgtJk',
    appId: '1:511621212818:android:ac33e3e35bfe6de9e5144b',
    messagingSenderId: '511621212818',
    projectId: 'loginflutter-c5ffa',
    storageBucket: 'loginflutter-c5ffa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABf_eTDENND1B_cw0K-xDdFy_jhKPVxhM',
    appId: '1:511621212818:ios:d16dc4d465116cd2e5144b',
    messagingSenderId: '511621212818',
    projectId: 'loginflutter-c5ffa',
    storageBucket: 'loginflutter-c5ffa.firebasestorage.app',
    iosBundleId: 'com.example.tarealog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABf_eTDENND1B_cw0K-xDdFy_jhKPVxhM',
    appId: '1:511621212818:ios:d16dc4d465116cd2e5144b',
    messagingSenderId: '511621212818',
    projectId: 'loginflutter-c5ffa',
    storageBucket: 'loginflutter-c5ffa.firebasestorage.app',
    iosBundleId: 'com.example.tarealog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZEc9XIEmPn02wmtXar0TfJt8qeqJQMhw',
    appId: '1:511621212818:web:034af4626728921ce5144b',
    messagingSenderId: '511621212818',
    projectId: 'loginflutter-c5ffa',
    authDomain: 'loginflutter-c5ffa.firebaseapp.com',
    storageBucket: 'loginflutter-c5ffa.firebasestorage.app',
    measurementId: 'G-SVYPWHG423',
  );
}
